# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

prysm-geth-001:
  global:
    main:
      network: pk-devnet-0
      engineEndpoint: http://geth-prysm-001:8551
      rpcEndpoint: http://geth-prysm-001:8545
      beaconEndpoint: http://prysm-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        pk-devnet-0: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.template-devnets.node_ingress.combined}>@bn-bootnode-1.pk-devnet-0.ethpandaops.io
    clientArgs:
      networks:
        pk-devnet-0:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://0a71b49f34c851a2dd3e63db3aab3a57a04c09c345b8b85ecf95f53535e24e77d89fd0c4485df3df16bc255e64d32248fb787b698d4001b6cfdf64edb1365725@67.207.92.66:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
            nethermind:
            geth:
              - --http.api=eth,net,web3,debug,admin,txpool
              - --http.vhosts=*
              - --networkid=7010913089
              - --syncmode=full
              - --bootnodes=enode://0a71b49f34c851a2dd3e63db3aab3a57a04c09c345b8b85ecf95f53535e24e77d89fd0c4485df3df16bc255e64d32248fb787b698d4001b6cfdf64edb1365725@67.207.92.66:30303?discport=30303
              - --rpc.allow-unprotected-txs
            erigon:
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QDAFFnciRSAB85s7OuXq4N7xsEDVhPoMCMCqj6G1XV4HTvHiHJKYhJYOVzFjGY3SB3Z8TJeJk0JFmq0e2fjaLf-GAZjHbKfPgmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-LK4QDaPsE_nU3-w-cbyi_-vS1QH_t2YhmwKXyAx49hMRrkhVpuO_LVF4nwXjDY7xNVDP4gsCq3zd1dfeEtlCOF6gSwGh2F0dG5ldHOIAAAAAAAAAwCEZXRoMpCvGZMiYBBxM___________gmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQLd6bgsMZ8J3kQ6-MFIvMYwCAoA0-mDtvp7O1enhoDjJYN0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QDAFFnciRSAB85s7OuXq4N7xsEDVhPoMCMCqj6G1XV4HTvHiHJKYhJYOVzFjGY3SB3Z8TJeJk0JFmq0e2fjaLf-GAZjHbKfPgmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-LK4QDaPsE_nU3-w-cbyi_-vS1QH_t2YhmwKXyAx49hMRrkhVpuO_LVF4nwXjDY7xNVDP4gsCq3zd1dfeEtlCOF6gSwGh2F0dG5ldHOIAAAAAAAAAwCEZXRoMpCvGZMiYBBxM___________gmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQLd6bgsMZ8J3kQ6-MFIvMYwCAoA0-mDtvp7O1enhoDjJYN0Y3CCIyiDdWRwgiMo
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QDAFFnciRSAB85s7OuXq4N7xsEDVhPoMCMCqj6G1XV4HTvHiHJKYhJYOVzFjGY3SB3Z8TJeJk0JFmq0e2fjaLf-GAZjHbKfPgmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-LK4QDaPsE_nU3-w-cbyi_-vS1QH_t2YhmwKXyAx49hMRrkhVpuO_LVF4nwXjDY7xNVDP4gsCq3zd1dfeEtlCOF6gSwGh2F0dG5ldHOIAAAAAAAAAwCEZXRoMpCvGZMiYBBxM___________gmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQLd6bgsMZ8J3kQ6-MFIvMYwCAoA0-mDtvp7O1enhoDjJYN0Y3CCIyiDdWRwgiMo
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QDAFFnciRSAB85s7OuXq4N7xsEDVhPoMCMCqj6G1XV4HTvHiHJKYhJYOVzFjGY3SB3Z8TJeJk0JFmq0e2fjaLf-GAZjHbKfPgmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-LK4QDaPsE_nU3-w-cbyi_-vS1QH_t2YhmwKXyAx49hMRrkhVpuO_LVF4nwXjDY7xNVDP4gsCq3zd1dfeEtlCOF6gSwGh2F0dG5ldHOIAAAAAAAAAwCEZXRoMpCvGZMiYBBxM___________gmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQLd6bgsMZ8J3kQ6-MFIvMYwCAoA0-mDtvp7O1enhoDjJYN0Y3CCIyiDdWRwgiMo
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=INFO
              - --light-client-data-serve=false
              - --bootstrap-node=enr:-Iq4QDAFFnciRSAB85s7OuXq4N7xsEDVhPoMCMCqj6G1XV4HTvHiHJKYhJYOVzFjGY3SB3Z8TJeJk0JFmq0e2fjaLf-GAZjHbKfPgmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-LK4QDaPsE_nU3-w-cbyi_-vS1QH_t2YhmwKXyAx49hMRrkhVpuO_LVF4nwXjDY7xNVDP4gsCq3zd1dfeEtlCOF6gSwGh2F0dG5ldHOIAAAAAAAAAwCEZXRoMpCvGZMiYBBxM___________gmlkgnY0gmlwhEPPXEKJc2VjcDI1NmsxoQLd6bgsMZ8J3kQ6-MFIvMYwCAoA0-mDtvp7O1enhoDjJYN0Y3CCIyiDdWRwgiMo


  geth:
    enabled: true
    fullnameOverride: geth-prysm-001
    image:
      repository: docker.ethquokkaops.io/dh/ethereum/client-go
      tag: stable
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31006
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: pk-devnet-0
      testnet: pk-devnet-0
      ethereum_network: pk-devnet-0
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.pk-devnet-0.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.pk-devnet-0.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.pk-devnet-0.ethpandaops.io/el/besu.json;
            ENODES_URI=https://config.pk-devnet-0.ethpandaops.io/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethereum/client-go:stable
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  prysm:
    checkpointSync:
      enabled: false
      addresses:
        pk-devnet-0: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.template-devnets.node_ingress.combined}>@bn-bootnode-1.pk-devnet-0.ethpandaops.io
    enabled: true
    fullnameOverride: prysm-geth-001
    image:
      repository: docker.ethquokkaops.io/gcr/prysmaticlabs/prysm/beacon-chain
      tag: latest
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32006
    podLabels:
      network: pk-devnet-0
      testnet: pk-devnet-0
      ethereum_network: pk-devnet-0
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: prysm-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.pk-devnet-0.ethpandaops.io/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.pk-devnet-0.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.pk-devnet-0.ethpandaops.io/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.pk-devnet-0.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.pk-devnet-0.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.pk-devnet-0.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
